version: '3.7'

services:
 drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - db
 db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
 db_data: {}
